# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /class/classes/akama031/CS100-Final-Project---official-group1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /class/classes/akama031/CS100-Final-Project---official-group1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"gmock\" \"gtest\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /class/classes/akama031/CS100-Final-Project---official-group1/CMakeFiles /class/classes/akama031/CS100-Final-Project---official-group1//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /class/classes/akama031/CS100-Final-Project---official-group1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named task_scheduler

# Build rule for target.
task_scheduler: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 task_scheduler
.PHONY : task_scheduler

# fast build rule for target.
task_scheduler/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_scheduler.dir/build.make CMakeFiles/task_scheduler.dir/build
.PHONY : task_scheduler/fast

#=============================================================================
# Target rules for targets named task_scheduler_test

# Build rule for target.
task_scheduler_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 task_scheduler_test
.PHONY : task_scheduler_test

# fast build rule for target.
task_scheduler_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_scheduler_test.dir/build.make CMakeFiles/task_scheduler_test.dir/build
.PHONY : task_scheduler_test/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

src/FileManager.o: src/FileManager.cpp.o
.PHONY : src/FileManager.o

# target to build an object file
src/FileManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_scheduler.dir/build.make CMakeFiles/task_scheduler.dir/src/FileManager.cpp.o
.PHONY : src/FileManager.cpp.o

src/FileManager.i: src/FileManager.cpp.i
.PHONY : src/FileManager.i

# target to preprocess a source file
src/FileManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_scheduler.dir/build.make CMakeFiles/task_scheduler.dir/src/FileManager.cpp.i
.PHONY : src/FileManager.cpp.i

src/FileManager.s: src/FileManager.cpp.s
.PHONY : src/FileManager.s

# target to generate assembly for a file
src/FileManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_scheduler.dir/build.make CMakeFiles/task_scheduler.dir/src/FileManager.cpp.s
.PHONY : src/FileManager.cpp.s

src/Scheduler.o: src/Scheduler.cpp.o
.PHONY : src/Scheduler.o

# target to build an object file
src/Scheduler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_scheduler.dir/build.make CMakeFiles/task_scheduler.dir/src/Scheduler.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_scheduler_test.dir/build.make CMakeFiles/task_scheduler_test.dir/src/Scheduler.cpp.o
.PHONY : src/Scheduler.cpp.o

src/Scheduler.i: src/Scheduler.cpp.i
.PHONY : src/Scheduler.i

# target to preprocess a source file
src/Scheduler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_scheduler.dir/build.make CMakeFiles/task_scheduler.dir/src/Scheduler.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_scheduler_test.dir/build.make CMakeFiles/task_scheduler_test.dir/src/Scheduler.cpp.i
.PHONY : src/Scheduler.cpp.i

src/Scheduler.s: src/Scheduler.cpp.s
.PHONY : src/Scheduler.s

# target to generate assembly for a file
src/Scheduler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_scheduler.dir/build.make CMakeFiles/task_scheduler.dir/src/Scheduler.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_scheduler_test.dir/build.make CMakeFiles/task_scheduler_test.dir/src/Scheduler.cpp.s
.PHONY : src/Scheduler.cpp.s

src/TaskManager.o: src/TaskManager.cpp.o
.PHONY : src/TaskManager.o

# target to build an object file
src/TaskManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_scheduler.dir/build.make CMakeFiles/task_scheduler.dir/src/TaskManager.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_scheduler_test.dir/build.make CMakeFiles/task_scheduler_test.dir/src/TaskManager.cpp.o
.PHONY : src/TaskManager.cpp.o

src/TaskManager.i: src/TaskManager.cpp.i
.PHONY : src/TaskManager.i

# target to preprocess a source file
src/TaskManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_scheduler.dir/build.make CMakeFiles/task_scheduler.dir/src/TaskManager.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_scheduler_test.dir/build.make CMakeFiles/task_scheduler_test.dir/src/TaskManager.cpp.i
.PHONY : src/TaskManager.cpp.i

src/TaskManager.s: src/TaskManager.cpp.s
.PHONY : src/TaskManager.s

# target to generate assembly for a file
src/TaskManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_scheduler.dir/build.make CMakeFiles/task_scheduler.dir/src/TaskManager.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_scheduler_test.dir/build.make CMakeFiles/task_scheduler_test.dir/src/TaskManager.cpp.s
.PHONY : src/TaskManager.cpp.s

src/UserInterface.o: src/UserInterface.cpp.o
.PHONY : src/UserInterface.o

# target to build an object file
src/UserInterface.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_scheduler.dir/build.make CMakeFiles/task_scheduler.dir/src/UserInterface.cpp.o
.PHONY : src/UserInterface.cpp.o

src/UserInterface.i: src/UserInterface.cpp.i
.PHONY : src/UserInterface.i

# target to preprocess a source file
src/UserInterface.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_scheduler.dir/build.make CMakeFiles/task_scheduler.dir/src/UserInterface.cpp.i
.PHONY : src/UserInterface.cpp.i

src/UserInterface.s: src/UserInterface.cpp.s
.PHONY : src/UserInterface.s

# target to generate assembly for a file
src/UserInterface.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_scheduler.dir/build.make CMakeFiles/task_scheduler.dir/src/UserInterface.cpp.s
.PHONY : src/UserInterface.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_scheduler.dir/build.make CMakeFiles/task_scheduler.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_scheduler.dir/build.make CMakeFiles/task_scheduler.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_scheduler.dir/build.make CMakeFiles/task_scheduler.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

tests/DateHelperTest.o: tests/DateHelperTest.cpp.o
.PHONY : tests/DateHelperTest.o

# target to build an object file
tests/DateHelperTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_scheduler_test.dir/build.make CMakeFiles/task_scheduler_test.dir/tests/DateHelperTest.cpp.o
.PHONY : tests/DateHelperTest.cpp.o

tests/DateHelperTest.i: tests/DateHelperTest.cpp.i
.PHONY : tests/DateHelperTest.i

# target to preprocess a source file
tests/DateHelperTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_scheduler_test.dir/build.make CMakeFiles/task_scheduler_test.dir/tests/DateHelperTest.cpp.i
.PHONY : tests/DateHelperTest.cpp.i

tests/DateHelperTest.s: tests/DateHelperTest.cpp.s
.PHONY : tests/DateHelperTest.s

# target to generate assembly for a file
tests/DateHelperTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_scheduler_test.dir/build.make CMakeFiles/task_scheduler_test.dir/tests/DateHelperTest.cpp.s
.PHONY : tests/DateHelperTest.cpp.s

tests/SchedulerTest.o: tests/SchedulerTest.cpp.o
.PHONY : tests/SchedulerTest.o

# target to build an object file
tests/SchedulerTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_scheduler_test.dir/build.make CMakeFiles/task_scheduler_test.dir/tests/SchedulerTest.cpp.o
.PHONY : tests/SchedulerTest.cpp.o

tests/SchedulerTest.i: tests/SchedulerTest.cpp.i
.PHONY : tests/SchedulerTest.i

# target to preprocess a source file
tests/SchedulerTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_scheduler_test.dir/build.make CMakeFiles/task_scheduler_test.dir/tests/SchedulerTest.cpp.i
.PHONY : tests/SchedulerTest.cpp.i

tests/SchedulerTest.s: tests/SchedulerTest.cpp.s
.PHONY : tests/SchedulerTest.s

# target to generate assembly for a file
tests/SchedulerTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_scheduler_test.dir/build.make CMakeFiles/task_scheduler_test.dir/tests/SchedulerTest.cpp.s
.PHONY : tests/SchedulerTest.cpp.s

tests/TaskTest.o: tests/TaskTest.cpp.o
.PHONY : tests/TaskTest.o

# target to build an object file
tests/TaskTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_scheduler_test.dir/build.make CMakeFiles/task_scheduler_test.dir/tests/TaskTest.cpp.o
.PHONY : tests/TaskTest.cpp.o

tests/TaskTest.i: tests/TaskTest.cpp.i
.PHONY : tests/TaskTest.i

# target to preprocess a source file
tests/TaskTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_scheduler_test.dir/build.make CMakeFiles/task_scheduler_test.dir/tests/TaskTest.cpp.i
.PHONY : tests/TaskTest.cpp.i

tests/TaskTest.s: tests/TaskTest.cpp.s
.PHONY : tests/TaskTest.s

# target to generate assembly for a file
tests/TaskTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_scheduler_test.dir/build.make CMakeFiles/task_scheduler_test.dir/tests/TaskTest.cpp.s
.PHONY : tests/TaskTest.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... task_scheduler"
	@echo "... task_scheduler_test"
	@echo "... src/FileManager.o"
	@echo "... src/FileManager.i"
	@echo "... src/FileManager.s"
	@echo "... src/Scheduler.o"
	@echo "... src/Scheduler.i"
	@echo "... src/Scheduler.s"
	@echo "... src/TaskManager.o"
	@echo "... src/TaskManager.i"
	@echo "... src/TaskManager.s"
	@echo "... src/UserInterface.o"
	@echo "... src/UserInterface.i"
	@echo "... src/UserInterface.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... tests/DateHelperTest.o"
	@echo "... tests/DateHelperTest.i"
	@echo "... tests/DateHelperTest.s"
	@echo "... tests/SchedulerTest.o"
	@echo "... tests/SchedulerTest.i"
	@echo "... tests/SchedulerTest.s"
	@echo "... tests/TaskTest.o"
	@echo "... tests/TaskTest.i"
	@echo "... tests/TaskTest.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

